### ISSUE TITLE
Define project methodology and workflow

### ISSUE THREAD

**Issue by stt-tomahl** [SKF/design-systems#30]
**What kind of methodology should we use?**

- Scrum
- Kanban
- None?

**Define sprint length?**

- 1 Week
- 2 Weeks
- 3 Weeks
- 4 Weeks

**Define sprint ceremonies?**
- Daily standup (time, length)
- Sprint start - Weekday
- Sprint end - Weekday
- Backlog grooming (day, time, length)
- Sprint planning (day, time, length)
- Sprint review (demo, retrospective) (day, time, length)
- Define product owner (if needed)

**Sprint demo**
- How long should the demo be?
- Who is invited?
- How and when do we communicate upcoming demos/releases?

**Comment by tobiasljungstrom** [comment]
From the discussions with the initial stakeholders, it seems reasonable to have a cadence similar to theirs, so that they can enjoy the regularity of releases and demos. So perhaps:

- A Kanban-like methodology, without estimates. (WIP-limits is something we can discuss later.)
- 2 week sprints
- Sprint start on Mondays and demos on Fridays.
- Backlog grooming/weekly planning once a week
