### ISSUE TITLE
Configure styelint-order to use idiomatic css ordering

### ISSUE THREAD

**Issue by tobiasljungstrom** [SKF/design-systems#35]
Sorting CSS properties alphabetically is fine, but serves no greater purpose than making the code look tidy. However, idiomatic css suggests grouping by logical function and I think this is beneficial for the mental model when writing css. See https://github.com/necolas/idiomatic-css#declaration-order. (There are other good suggestions on that page as well.)

See this page for an example config:
https://github.com/ream88/stylelint-config-idiomatic-order

**Comment by stt-tomahl** [comment]
I used the idiomatic sorting before but many team members complained about it because they had to learn something new that didn't provide a real value in the end. They had to move props up-and-down until the linter was satisfied which many experienced as unnecessary work. Everyone knows how to sort a-z, but not the idiomatic way of sorting of props.

I can go with either. :)

**Comment by tobiasljungstrom** [comment]
It hinges on if it can be formatted automatically in your editor. If not hen alphabetically is fine. But I think it should be possible?
